name: Build and Release APK

# Trigger the workflow on pushing a tag or manually
on:
  push:
    branches:
      - master
    tags:
      # Example: v1.0.0
      - 'v*'
  workflow_dispatch: # This allows manual triggers via GitHub UI

jobs:
  # Android job
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Decode Keystore
        run: echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Grant gradlew execute
        run: chmod +x gradlew
      - name: Build APK
        run: |
          ./gradlew :composeApp:assembleRelease
          mv composeApp/build/outputs/apk/release/composeApp-release.apk composeApp/build/outputs/apk/release/ACCA_Buddy.apk
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/release/ACCA_Buddy.apk
      - name: Clean up keystore file
        run: |
          rm -f keystore.jks

  # macOS job
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant gradlew execute
        run: chmod +x gradlew
      - name: Build DMG
        run: ./gradlew :composeApp:packageReleaseDmg
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: composeApp/build/compose/binaries/**/*.dmg

  # Windows job
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant gradlew execute
        run: chmod +x gradlew
      - name: Build EXE
        run: ./gradlew :composeApp:packageReleaseExe
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: composeApp/build/compose/binaries/**/*.exe

  release:
    needs: [build-android, build-macos, build-windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Download artifacts from other jobs
      - uses: actions/download-artifact@v4
        with:
          name: android-apk
          path: release/
      - uses: actions/download-artifact@v4
        with:
          name: mac-dmg
          path: release/
      - uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: release/

      - name: Flatten release folder
        run: |
          find release -name "*.dmg" -exec mv {} release/ \;
          find release -name "*.exe" -exec mv {} release/ \;

      - name: Log release folder
        run: ls -R release

      # Upload all artifacts
      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true
          files: |
            release/*.dmg
            release/*.exe
            release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}